# Generated by Django 4.0.3 on 2022-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mail',
            field=models.CharField(max_length=100),
        ),
    ]
