# Generated by Django 4.0.3 on 2022-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0003_mail_trycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklist',
            name='service',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
