# Generated by Django 4.0.3 on 2022-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0004_blocklist_service_alter_blocklist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trycount',
            name='service',
            field=models.CharField(default='deneme', max_length=100),
            preserve_default=False,
        ),
    ]
