# Generated by Django 4.0.3 on 2022-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=1000)),
                ('targetuser', models.CharField(max_length=1000)),
                ('resourceuser', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ftplog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='fuzzinglog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='httplog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='sshlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
    ]
