# Generated by Django 4.0.3 on 2022-06-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogData', '0002_fuzzinglog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='summaryauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumcount', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='summaryftp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumcount', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='summaryfuzzing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumcount', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='summaryhttp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumcount', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='summaryssh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumcount', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=1000)),
            ],
        ),
    ]
