# Generated by Django 4.0.3 on 2022-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogData', '0003_summaryauth_summaryftp_summaryfuzzing_summaryhttp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryauth',
            old_name='ip',
            new_name='resourceuser',
        ),
        migrations.AddField(
            model_name='summaryauth',
            name='targetuser',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryftp',
            name='username',
            field=models.CharField(default='yusuf', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryssh',
            name='username',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
